language: node_js

stages:
  - install
  - test
  - deploy

jobs:
  include:
    - stage: install
      script: npm install
    - stage: test
      script: npm test
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: hacker-news-page
        api_key: $HEROKU_AUTH_TOKEN
